In [38]:
import numpy as np

In [39]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [40]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [41]:
#Get Dimensions
a.ndim # 1
b.ndim # 2

2

In [42]:
#Get shape
b.shape #عدد الصفوف و عدد الاعمدة

(2, 3)

In [43]:
# Get type
a.dtype #dtype('int32')
b.dtype

dtype('float64')

In [44]:
# Get size
a.itemsize

4

In [45]:
#Get total size 
a.nbytes #a.size * a.itemsize

12

In [46]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
#Get a specific row
# a[: , 2]
#Get a specific element
a [1,5]

13

In [48]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
b [:,1,:]

array([[3, 4],
       [7, 8]])

Initializing Different Types of Arrays


In [51]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [53]:
#Random numbers
np.random.rand(3,5)

array([[0.68954928, 0.14274701, 0.45915847, 0.44924389, 0.66407616],
       [0.16083881, 0.08684434, 0.99040961, 0.1111654 , 0.11699473],
       [0.26362858, 0.85676884, 0.38679366, 0.11534841, 0.11845343]])

In [56]:
np.random.randn(6) # negative and positive numbers value

array([-0.9924263 , -1.68327404, -1.10100024,  0.05869317, -1.07289271,
       -0.90074359])

In [57]:
np.random.randint(1,150) # nay random number from 1 to 150

89

In [58]:
np.random.randint(5,100,4) #any "integer" random number between (5,100) in 1D array "size = 4"

array([31, 29, 79, 82])

In [60]:
np.random.randint(5,100,(2,3))

array([[94, 39, 29],
       [68, 93, 32]])

In [61]:
np.random.randint((15,40)) # 2 integer random number the first between (0,15) and the secound between(0,40)

array([5, 2])

In [64]:
np.random.randint(20,size=(2,2)) # any integer random nums from 0 to 20 with size 2,2

array([[14,  5],
       [ 0, 19]])

In [65]:
np.arange(1,30) # Sequence number from 1 to 30

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [66]:
np.random.random_sample(a.shape)

array([[0.20424029, 0.93280343, 0.05907609, 0.80832934, 0.33178259,
        0.19057499, 0.91024358],
       [0.05175135, 0.593334  , 0.39673383, 0.29205323, 0.66495769,
        0.1100785 , 0.8266879 ]])

In [69]:
np.identity(4) # unit matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0) # repeat arr three times 
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [77]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics

In [78]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [79]:
a+2

array([3, 4, 5, 6, 7])

In [80]:
b = np.array([1,0,0,1,1])
a+b

array([2, 2, 3, 5, 6])

In [81]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [82]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

Linear Algebra

In [84]:
a = np.full((2,3),3)
print(a)

b = np.full((3,2), 4)
print(b)

np.matmul(a,b) #Matrix multiplication

[[3 3 3]
 [3 3 3]]
[[4 4]
 [4 4]
 [4 4]]


array([[36, 36],
       [36, 36]])

In [85]:
#find the determinant
i = np.identity(3)
np.linalg.det(i)

1.0

Statistics

In [86]:
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.max(y)

6

Miscellaneous

In [88]:
np.genfromtxt('data.txt', delimiter=',')

array(nan)