In [99]:
import numpy as np

Create numpy array

In [100]:
a = np.array([1,3,5,2,6,4])

In [101]:
print(a)  

[1 3 5 2 6 4]


In [102]:
b = np.array([[1,5,7,19,2],[2,4,3,34,27]]) #two dimensionss array
print(b)

[[ 1  5  7 19  2]
 [ 2  4  3 34 27]]


In [103]:
c = np.array([1.2,5.9])

In [104]:
a.ndim #عدد أبعاد الاراى

1

In [105]:
b.ndim

2

In [106]:
a.shape #Get Shape

(6,)

In [107]:
b.shape

(2, 5)

In [108]:
a.dtype #data type of array 

dtype('int32')

In [109]:
c.dtype

dtype('float64')

In [110]:
a.itemsize #number of bytes of array "size of data type"

4

In [111]:
c.itemsize

8

In [112]:
a.size #number of element 

6

In [113]:
b.size

10

In [114]:
a.nbytes # a.size * a.itemsize

24

In [115]:
b.nbytes

40

In [116]:
#[r,c] 
b[1,3] #access to specific element

34

In [117]:
a[-4] #access from the end

5

In [118]:
b[1,:] # Get specific row 

array([ 2,  4,  3, 34, 27])

In [119]:
b[:,3] # Get specific column

array([19, 34])

In [120]:
b[0,0:3:3]

array([1])

In [121]:
b[0,0:5:2]

array([1, 7, 2])

In [122]:
b[0,0:5:4]

array([1, 2])

In [123]:
b[0,2:5:5]

array([7])

In [124]:
b[0,1:3:2]

array([5])

In [125]:
a[2]=40 # replace value in array
print(a)

[ 1  3 40  2  6  4]


In [126]:
b[:,3]=[50,60] # replace column in array
print(b)

[[ 1  5  7 50  2]
 [ 2  4  3 60 27]]


In [127]:
b[1,:]=[3,5,17,22,30] #replace row in array
print(b)

[[ 1  5  7 50  2]
 [ 3  5 17 22 30]]


=> 3D array

In [128]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[17,18,19]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]]


In [129]:
d.shape

(2, 3, 3)

In [130]:
d[0,2,2] # access to specific element in 3D array

9

In [131]:
d[:,1,:]

array([[ 4,  5,  6],
       [13, 14, 15]])

In [132]:
d[0,2,2]=20

In [133]:
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8 20]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]]


Initialize different types of arrays

In [134]:
#All 0s matrix
zero = np.zeros(4)
print(zero)

[0. 0. 0. 0.]


In [135]:
zeros = np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [136]:
zeros3 = np.zeros((2,3,4))
print(zeros3)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [137]:
#All 1s matrix
one = np.ones(3)
print(one)

[1. 1. 1.]


In [138]:
oneInt = np.ones(4,dtype='int32') #identify data type
print(oneInt)

[1 1 1 1]


In [139]:
onesInt = np.ones((3,2,4),dtype='int32')
print(onesInt)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [140]:
#Any other number
#                (r,c),numbers
anyNum = np.full((3,5),20)
print(anyNum)

[[20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]]


In [141]:
anyNum2 = np.full((2,4),((1,3,4,5),(6,9,7,8)))
print(anyNum2)

[[1 3 4 5]
 [6 9 7 8]]


In [142]:
#Any other number (full_like)
anyNumFL = np.full_like(d,5)
print(anyNumFL)

[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]


In [143]:
#Random numbers
np.random.rand(2,4)

array([[0.98077073, 0.01164357, 0.7989206 , 0.71167197],
       [0.90899872, 0.33964472, 0.51357858, 0.70686757]])

In [144]:
np.random.rand(5)

array([0.54167513, 0.10455226, 0.299714  , 0.49596408, 0.09689615])

In [145]:
np.random.random(4)

array([0.00897828, 0.95134816, 0.40024926, 0.81792937])

In [146]:
np.random.randn(5) #Positive and negative random numbers

array([-0.47701886, -0.85443676, -1.41650658,  0.89561385,  0.95818762])

In [147]:
np.random.randint(1,100) #integer random number between (1,100)

68

In [148]:
np.random.randint(3,50,5) #integer random number between (3,50) in 1D array "size = 5"

array([29, 45, 47, 35, 10])

In [149]:
np.random.randint(30,100,(2,3))

array([[42, 53, 86],
       [66, 30, 59]])

In [150]:
np.random.randint((20,30)) # 2 integer random number the first between (0,20) and the secound between(0,30)

array([19, 23])

In [151]:
np.random.randint(10,size=(3,3))

array([[1, 6, 2],
       [1, 4, 3],
       [9, 7, 9]])

In [152]:
np.random.randint(-10,10,size=(3,3))

array([[ 6, -9, -7],
       [ 3,  3, -6],
       [ 1,  1, -9]])

In [153]:
np.random.random((2,3)) # random 2D array

array([[0.34532372, 0.55450409, 0.19650335],
       [0.78874133, 0.10787271, 0.75111295]])

In [154]:
np.arange(1,10) # Sequence number from 1 to 9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
np.random.random_sample(a.shape)

array([0.62796921, 0.30230958, 0.90672374, 0.49401494, 0.77239948,
       0.0203443 ])

In [156]:
np.random.random_sample(b.shape)

array([[0.21574242, 0.22497253, 0.09340167, 0.60395886, 0.23065885],
       [0.10790353, 0.91967833, 0.09425777, 0.15758103, 0.74928899]])

In [157]:
np.identity(3) #Unit matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [158]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [159]:
r1 = np.repeat(a,3)
print(r1)

[ 1  1  1  3  3  3 40 40 40  2  2  2  6  6  6  4  4  4]


In [160]:
r2 = np.repeat(b,3,axis=0)
print(r2)

[[ 1  5  7 50  2]
 [ 1  5  7 50  2]
 [ 1  5  7 50  2]
 [ 3  5 17 22 30]
 [ 3  5 17 22 30]
 [ 3  5 17 22 30]]


In [161]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [162]:
#array copy
e=a.copy()
print(e)
e[3]=50
print(e)
print(a)

[ 1  3 40  2  6  4]
[ 1  3 40 50  6  4]
[ 1  3 40  2  6  4]


Mathemtics

In [163]:
print(a)


[ 1  3 40  2  6  4]


In [164]:
a+2

array([ 3,  5, 42,  4,  8,  6])

In [165]:
a-2

array([-1,  1, 38,  0,  4,  2])

In [166]:
a*3

array([  3,   9, 120,   6,  18,  12])

In [167]:
a/4

array([ 0.25,  0.75, 10.  ,  0.5 ,  1.5 ,  1.  ])

In [168]:
f = np.array([1,2,3,4,5,6])
a+f

array([ 2,  5, 43,  6, 11, 10])

In [169]:
a**2

array([   1,    9, 1600,    4,   36,   16], dtype=int32)

In [170]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.14112001,  0.74511316,  0.90929743, -0.2794155 ,
       -0.7568025 ])

In [171]:
#Take the cos
np.cos(a)

array([ 0.54030231, -0.9899925 , -0.66693806, -0.41614684,  0.96017029,
       -0.65364362])

In [172]:
#Take the tan
np.tan(a)

array([ 1.55740772, -0.14254654, -1.11721493, -2.18503986, -0.29100619,
        1.15782128])

Linear Algebra

In [173]:
g = np.full((2,3),3)
print(g)

h = np.full((3,2), 4)
print(h)

np.matmul(g,h) #Matrix multiplication

[[3 3 3]
 [3 3 3]]
[[4 4]
 [4 4]
 [4 4]]


array([[36, 36],
       [36, 36]])

In [174]:
#find the determinant
i = np.identity(3)
np.linalg.det(i)

1.0

In [175]:
j=np.full((2,2),[[2,3],[4,5]])
np.linalg.det(j)

-2.0

Statistics

In [176]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
stats.ndim

2

In [178]:
np.max(stats)

6

In [179]:
np.max(stats, axis=1)

array([3, 6])

In [180]:
np.min(stats)

1

In [181]:
np.min(stats,axis=1)

array([1, 4])

In [182]:
np.sum(stats) #Sum all the elements of the array

21

In [183]:
np.sum(stats, axis=0) #Add the elements of the row0 and the elements of the row1 of the matrix

array([5, 7, 9])

Reorganizing Arrays

In [184]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [185]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [186]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [187]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [188]:
np.vstack([v2,v2,v1,v2])

array([[5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [189]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [190]:
np.hstack((h1,h2,h1))

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

Miscellaneous


Load Data from File

In [192]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

-2147483648


Boolean Masking and Advanced Indexing

In [ ]:
filedata>50

array([[False, False, False,  True, False, False, False,  True,  True,
         True],
       [ True, False,  True, False,  True, False, False, False,  True,
         True],
       [ True,  True,  True, False, False, False,  True, False, False,
         True]])

In [ ]:
filedata[filedata>50]

array([56, 59, 63, 90, 88, 77, 79, 91, 60, 61, 68, 97, 70, 97])

In [ ]:
np.any(filedata > 50 ,axis=0)

NameError: name 'filedata' is not defined